apiVersion: v1
kind: Pod
metadata:
    name: web-app
    labels:
        app: my-app
spec:
    containers:
        - name: web-1
          image: nginx
        - name: db-1
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
